#!/usr/bin/env bash
#Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
sudo touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
while true
do
  trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' 15
  trap 'rm /var/run/myscript.pid; exit' 3
  trap 'echo "Y U no love me?!"' 2
  echo "To infinity and beyond"
  sleep 2
done
