#!/usr/bin/env bash
#configure a server so that you can connect to it
#without a password
Host 52.86.222.156
IdentityFile ~/.ssh/school
PasswordAuthentication no
SendEnv LANG LC_*
HashKnownHosts yes
GSSAPIAuthentication yes
