#!/usr/bin/env bash
#configure a server so that you can connect to it
#without a password
Host 35.153.194.219
IdentityFile ~/.ssh/school
PasswordAuthentication no
SendEnv LANG LC_*
HashKnownHosts yes
GSSAPIAuthentication yes
